version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: code-server_server_1
      APP_PORT: 8080

  server:
    image: codercom/code-server:4.19.1@sha256:993c381c28a3738b903ac21180f5f9dab8f2aa547bbb0b9d69bea558691e10d3
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD
