version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: homebox_web_1
      APP_PORT: 7745
    
  web:
    image: ghcr.io/hay-kot/homebox:v0.10.1-rootless@sha256:644bd92d827c7ac2c491fad8fd4607bb2b3598a92efc40236d743619c95c7050
    restart: on-failure
    user: 1000:1000
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - ${APP_DATA_DIR}/data:/data/
