version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefox_server_1
      APP_PORT: 3000

  server:
    image: linuxserver/firefox:116.0.3@sha256:27751e123a4a17be1e60f672ff79c1f40bbc7488d4b470fa8f49633131233486
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"
